/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cand.app;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import javax.annotation.PostConstruct;
import java.net.InetAddress;
import java.net.UnknownHostException;

@SpringBootApplication
@SecurityScheme(name = "javainuseapi", scheme = "basic", type = SecuritySchemeType.HTTP, in = SecuritySchemeIn.HEADER)
@OpenAPIDefinition(info = @Info(title = "Customer API", version = "2.0", description = "Customer Information"))
public class App {

    @Value("${server.port}")
    private String port;

    private String host = InetAddress.getLocalHost().getHostAddress();

    public App() throws UnknownHostException {
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @PostConstruct
    public void init() {
        System.out.printf("""
                Using Spring-Doc-OpenAPI-
                http://%s:%s/v3/api-docs/
                http://%s:%s/swagger-ui/index.html

                """, this.host, port, this.host, port);
    }
}
